const projectsList = [
  {
    title: "Volunter Web App",
    type: "back-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "bbc.png",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "Chemical Analysis",
    type: "front-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "chemical.jpg",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "Electronic Record",
    type: "back-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "Electronic Records Management Systems.jpg",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "Machine Learning System",
    type: "back-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "machine learning.jpg",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "test project one",
    type: "front-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "img_github_logo.png",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "test project two",
    type: "plain-js",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "img_github_logo.png",
    demoLink: "",
    sourceCodeLink: "",
  },
  {
    title: "test project three",
    type: "back-end",
    techUsed: "html, css, js",
    desc: "A Web App that allows the users to search, research and book a socially conscious travel adventure.",
    img: "img_github_logo.png",
    demoLink: "",
    sourceCodeLink: "",
  },
];

export default projectsList;
